# Android CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

references:
  workspace_root: &workspace_root
    ~/libFM

  container_config: &container_config
    docker:
      - image: circleci/android:api-28

    working_directory: *workspace_root

    environment:
      TERM: dumb
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g

  attach_workspace: &attach_workspace
      attach_workspace:
        at: *workspace_root

  general_cache_key: &general_cache_key
    key: app-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
    # key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          <<: *general_cache_key
          paths:
            - ~/.gradle
            - "~/.m2"

      - run:
          name: Debug Build
          command: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
  check:
    <<: *container_config
    steps:
      - *attach_workspace
      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Checks
          command: ./gradlew lintDebug ktlintCheck
          # command: ./gradlew lint test

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/reports/
          destination: lint_reports/

      # - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #     path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples


workflows:
  version: 2

  build_check_tests:
    jobs:
      - build
      - check:
          requires:
            - build









